[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "iatdocs-engine"
version = "0.8.9"
description = "Python-native controlled-document compiler and GitHub Enterprise Pages reader for GS-2210 artifacts"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "Jinja2==3.1.6",
  "mistune==3.2.1"
]
authors = [
  {name = "Matthew S. Novak"}
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Operating System :: OS Independent",
  "License :: Other/Proprietary License"
]

[project.scripts]
iatdocs = "iatdocs.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["iatdocs*"]
